using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PDQ.Framework.Web.CssIcons
{
    public enum GlyphStandard
    {
Glass, // glass
Leaf, // leaf
Dog, // dog
User, // user
Girl, // girl
Car, // car
UserAdd, // user-add
UserRemove, // user-remove
Film, // film
Magic, // magic
Envelope, // envelope
Camera, // camera
Heart, // heart
BeachUmbrella, // beach-umbrella
Train, // train
Print, // print
Bin, // bin
Music, // music
Note, // note
HeartEmpty, // heart-empty
Home, // home
Snowflake, // snowflake
Fire, // fire
Magnet, // magnet
Parents, // parents
Binoculars, // binoculars
Road, // road
Search, // search
Cars, // cars
Notes2, // notes-2
Pencil, // pencil
Bus, // bus
WifiAlt, // wifi-alt
Luggage, // luggage
OldMan, // old-man
Woman, // woman
File, // file
Coins, // coins
Airplane, // airplane
Notes, // notes
Stats, // stats
Charts, // charts
PieChart, // pie-chart
Group, // group
Keys, // keys
Calendar, // calendar
Router, // router
CameraSmall, // camera-small
StarEmpty, // star-empty
Star, // star
Link, // link
EyeOpen, // eye-open
EyeClose, // eye-close
Alarm, // alarm
Clock, // clock
Stopwatch, // stopwatch
Projector, // projector
History, // history
Truck, // truck
Cargo, // cargo
Compass, // compass
Keynote, // keynote
Paperclip, // paperclip
Power, // power
Lightbulb, // lightbulb
Tag, // tag
Tags, // tags
Cleaning, // cleaning
Ruler, // ruler
Gift, // gift
Umbrella, // umbrella
Book, // book
Bookmark, // bookmark
Wifi, // wifi
Cup, // cup
Stroller, // stroller
Headphones, // headphones
Headset, // headset
WarningSign, // warning-sign
Signal, // signal
Retweet, // retweet
Refresh, // refresh
Roundabout, // roundabout
Random, // random
Heat, // heat
Repeat, // repeat
Display, // display
LogBook, // log-book
AddressBook, // address-book
Building, // building
Eyedropper, // eyedropper
Adjust, // adjust
Tint, // tint
Crop, // crop
VectorPathSquare, // vector-path-square
VectorPathCircle, // vector-path-circle
VectorPathPolygon, // vector-path-polygon
VectorPathLine, // vector-path-line
VectorPathCurve, // vector-path-curve
VectorPathAll, // vector-path-all
Font, // font
Italic, // italic
Bold, // bold
TextUnderline, // text-underline
TextStrike, // text-strike
TextHeight, // text-height
TextWidth, // text-width
TextResize, // text-resize
LeftIndent, // left-indent
RightIndent, // right-indent
AlignLeft, // align-left
AlignCenter, // align-center
AlignRight, // align-right
Justify, // justify
List, // list
TextSmaller, // text-smaller
TextBigger, // text-bigger
Embed, // embed
EmbedClose, // embed-close
Table, // table
MessageFull, // message-full
MessageEmpty, // message-empty
MessageIn, // message-in
MessageOut, // message-out
MessagePlus, // message-plus
MessageMinus, // message-minus
MessageBan, // message-ban
MessageFlag, // message-flag
MessageLock, // message-lock
MessageNew, // message-new
Inbox, // inbox
InboxPlus, // inbox-plus
InboxMinus, // inbox-minus
InboxLock, // inbox-lock
InboxIn, // inbox-in
InboxOut, // inbox-out
Cogwheel, // cogwheel
Cogwheels, // cogwheels
Picture, // picture
AdjustAlt, // adjust-alt
DatabaseLock, // database-lock
DatabasePlus, // database-plus
DatabaseMinus, // database-minus
DatabaseBan, // database-ban
FolderOpen, // folder-open
FolderPlus, // folder-plus
FolderMinus, // folder-minus
FolderLock, // folder-lock
FolderFlag, // folder-flag
FolderNew, // folder-new
Edit, // edit
NewWindow, // new-window
Check, // check
Unchecked, // unchecked
MoreWindows, // more-windows
ShowBigThumbnails, // show-big-thumbnails
ShowThumbnails, // show-thumbnails
ShowThumbnailsWithLines, // show-thumbnails-with-lines
ShowLines, // show-lines
Playlist, // playlist
Imac, // imac
Macbook, // macbook
Ipad, // ipad
Iphone, // iphone
IphoneTransfer, // iphone-transfer
IphoneExchange, // iphone-exchange
Ipod, // ipod
IpodShuffle, // ipod-shuffle
EarPlugs, // ear-plugs
Record, // record
StepBackward, // step-backward
FastBackward, // fast-backward
Rewind, // rewind
Play, // play
Pause, // pause
Stop, // stop
Forward, // forward
FastForward, // fast-forward
StepForward, // step-forward
Eject, // eject
FacetimeVideo, // facetime-video
DownloadAlt, // download-alt
Mute, // mute
VolumeDown, // volume-down
VolumeUp, // volume-up
Screenshot, // screenshot
Move, // move
More, // more
BrightnessReduce, // brightness-reduce
BrightnessIncrease, // brightness-increase
CirclePlus, // circle-plus
CircleMinus, // circle-minus
CircleRemove, // circle-remove
CircleOk, // circle-ok
CircleQuestionMark, // circle-question-mark
CircleInfo, // circle-info
CircleExclamationMark, // circle-exclamation-mark
Remove, // remove
Ok, // ok
Ban, // ban
Download, // download
Upload, // upload
ShoppingCart, // shopping-cart
Lock, // lock
Unlock, // unlock
Electricity, // electricity
Ok2, // ok-2
Remove2, // remove-2
CartOut, // cart-out
CartIn, // cart-in
LeftArrow, // left-arrow
RightArrow, // right-arrow
DownArrow, // down-arrow
UpArrow, // up-arrow
ResizeSmall, // resize-small
ResizeFull, // resize-full
CircleArrowLeft, // circle-arrow-left
CircleArrowRight, // circle-arrow-right
CircleArrowTop, // circle-arrow-top
CircleArrowDown, // circle-arrow-down
PlayButton, // play-button
Unshare, // unshare
Share, // share
ChevronRight, // chevron-right
ChevronLeft, // chevron-left
Bluetooth, // bluetooth
Euro, // euro
Usd, // usd
Gbp, // gbp
Retweet2, // retweet-2
Moon, // moon
Sun, // sun
Cloud, // cloud
Direction, // direction
Brush, // brush
Pen, // pen
ZoomIn, // zoom-in
ZoomOut, // zoom-out
Pin, // pin
Albums, // albums
RotationLock, // rotation-lock
Flash, // flash
GoogleMaps, // google-maps
Anchor, // anchor
Conversation, // conversation
Chat, // chat
Male, // male
Female, // female
Asterisk, // asterisk
Divide, // divide
SnorkelDiving, // snorkel-diving
ScubaDiving, // scuba-diving
OxygenBottle, // oxygen-bottle
Fins, // fins
Fishes, // fishes
Boat, // boat
Delete, // delete
SheriffsStar, // sheriffs-star
Qrcode, // qrcode
Barcode, // barcode
Pool, // pool
Buoy, // buoy
Spade, // spade
Bank, // bank
Vcard, // vcard
ElectricalPlug, // electrical-plug
Flag, // flag
CreditCard, // credit-card
KeyboardWireless, // keyboard-wireless
KeyboardWired, // keyboard-wired
Shield, // shield
Ring, // ring
Cake, // cake
Drink, // drink
Beer, // beer
FastFood, // fast-food
Cutlery, // cutlery
Pizza, // pizza
BirthdayCake, // birthday-cake
Tablet, // tablet
Settings, // settings
Bullets, // bullets
Cardio, // cardio
TShirt, // t-shirt
Pants, // pants
Sweater, // sweater
Fabric, // fabric
Leather, // leather
Scissors, // scissors
Bomb, // bomb
Skull, // skull
Celebration, // celebration
TeaKettle, // tea-kettle
FrenchPress, // french-press
CoffeeCup, // coffee-cup
Pot, // pot
Grater, // grater
Kettle, // kettle
Hospital, // hospital
HospitalH, // hospital-h
Microphone, // microphone
Webcam, // webcam
TempleChristianityChurch, // temple-christianity-church
TempleIslam, // temple-islam
TempleHindu, // temple-hindu
TempleBuddhist, // temple-buddhist
Bicycle, // bicycle
LifePreserver, // life-preserver
ShareAlt, // share-alt
Comments, // comments
Flower, // flower
Baseball, // baseball
Rugby, // rugby
Ax, // ax
TableTennis, // table-tennis
Bowling, // bowling
TreeConifer, // tree-conifer
TreeDeciduous, // tree-deciduous
MoreItems, // more-items
Sort, // sort
Filter, // filter
Gamepad, // gamepad
PlayingDices, // playing-dices
Calculator, // calculator
Tie, // tie
Wallet, // wallet
Piano, // piano
Sampler, // sampler
Podium, // podium
SoccerBall, // soccer-ball
Blog, // blog
Dashboard, // dashboard
Certificate, // certificate
Bell, // bell
Candle, // candle
Pushpin, // pushpin
IphoneShake, // iphone-shake
PinFlag, // pin-flag
Turtle, // turtle
Rabbit, // rabbit
Globe, // globe
Briefcase, // briefcase
Hdd, // hdd
ThumbsUp, // thumbs-up
ThumbsDown, // thumbs-down
HandRight, // hand-right
HandLeft, // hand-left
HandUp, // hand-up
HandDown, // hand-down
Fullscreen, // fullscreen
ShoppingBag, // shopping-bag
BookOpen, // book-open
Nameplate, // nameplate
NameplateAlt, // nameplate-alt
Vases, // vases
Bullhorn, // bullhorn
Dumbbell, // dumbbell
Suitcase, // suitcase
FileImport, // file-import
FileExport, // file-export
Bug, // bug
Crown, // crown
Smoking, // smoking
CloudDownload, // cloud-download
CloudUpload, // cloud-upload
Restart, // restart
SecurityCamera, // security-camera
Expand, // expand
Collapse, // collapse
CollapseTop, // collapse-top
GlobeAF, // globe-af
Global, // global
Spray, // spray
Nails, // nails
ClawHammer, // claw-hammer
ClassicHammer, // classic-hammer
HandSaw, // hand-saw
Riflescope, // riflescope
ElectricalSocketEU, // electrical-socket-eu
ElectricalSocketUS, // electrical-socket-us
MessageForward, // message-forward
CoatHanger, // coat-hanger
Dress, // dress
Bathrobe, // bathrobe
Shirt, // shirt
Underwear, // underwear
LogIn, // log-in
LogOut, // log-out
Exit, // exit
NewWindowAlt, // new-window-alt
VideoSS, // video-sd
VideoHd, // video-hd
Subtitles, // subtitles
SoundStereo, // sound-stereo
SoundDolby, // sound-dolby
Sound51, // sound-5-1
Sound61, // sound-6-1
Sound71, // sound-7-1
CopyrightMark, // copyright-mark
RegistrationMark, // registration-mark
Radar, // radar
Skateboard, // skateboard
GolfCourse, // golf-course
Sorting, // sorting
SortByAlphabet, // sort-by-alphabet
SortByAlphabetAlt, // sort-by-alphabet-alt
SortByOrder, // sort-by-order
SortByOrderAlt, // sort-by-order-alt
SortByAttributes, // sort-by-attributes
SortByAttributesAlt, // sort-by-attributes-alt
Compressed, // compressed
Package, // package
CloudPlus, // cloud-plus
CloudMinus, // cloud-minus
DiskSave, // disk-save
DiskOpen, // disk-open
DiskSaved, // disk-saved
DiskRemove, // disk-remove
DiskImport, // disk-import
DiskExport, // disk-export
Tower, // tower
Send, // send
GitBranch, // git-branch
GitCreate, // git-create
GitPrivate, // git-private
GitDelete, // git-delete
GitMerge, // git-merge
GitPullRequest, // git-pull-request
GitCompare, // git-compare
GitCommit, // git-commit
ConstructionCone, // construction-cone
ShoeSteps, // shoe-steps
Plus, // plus
Minus, // minus
Redo, // redo
Undo, // undo
Golf, // golf
Hockey, // hockey
Pipe, // pipe
Wrench, // wrench
FolderClosed, // folder-closed
PhoneAlt, // phone-alt
Earphone, // earphone
FloppyDisk, // floppy-disk
FloppySaved, // floppy-saved
FloppyRemove, // floppy-remove
FloppySave, // floppy-save
FloppyOpen, // floppy-open
Translate, // translate
Fax, // fax
Factory, // factory
ShopWindow, // shop-window
Shop, // shop
Kiosk, // kiosk
KioskWheels, // kiosk-wheels
KioskLight, // kiosk-light
KioskFood, // kiosk-food
Transfer, // transfer
Money, // money
Header, // header
Blacksmith, // blacksmith
SawBlade, // saw-blade
Basketball, // basketball
Server, // server
ServerPlus, // server-plus
ServerMinus, // server-minus
ServerBan, // server-ban
ServerFlag, // server-flag
ServerLock, // server-lock
ServerNew, // server-new
ChargingStation, // charging-station
GasStation, // gas-station
Target, // target
BedAlt, // bed-alt
MosquitoNet, // mosquito-net
DiningSet, // dining-set
PlateOfFood, // plate-of-food
HygieneKit, // hygiene-kit
Blackboard, // blackboard
Marriage, // marriage
Bucket, // bucket
NoneColorSwatch, // none-color-swatch
BringForward, // bring-forward
BringToFront, // bring-to-front
SendBackward, // send-backward
SendToBack, // send-to-back
FitFrameToImage, // fit-frame-to-image
FitImageToFrame, // fit-image-to-frame
MultipleDisplays, // multiple-displays
Handshake, // handshake
Child, // child
BabyFormula, // baby-formula
Medicine, // medicine
AtvVehicle, // atv-vehicle
Motorcycle, // motorcycle
Bed, // bed
Tent, // tent
Glasses, // glasses
Sunglasses, // sunglasses
Family, // family
Education, // education
Shoes, // shoes
Map, // map
Cd, // cd
Alert, // alert
PiggyBank, // piggy-bank
StarHalf, // star-half
Cluster, // cluster
Flowchart, // flowchart
Commodities, // commodities
Duplicate, // duplicate
Copy, // copy
Paste, // paste
BathBathtub, // bath-bathtub
BathShower, // bath-shower
Shower, // shower
MenuHamburger, // menu-hamburger
OptionVertical, // option-vertical
OptionHorizontal, // option-horizontal
CurrencyConversion, // currency-conversion
UserBan, // user-ban
UserLock, // user-lock
UserFlag, // user-flag
UserAsterisk, // user-asterisk
UserAlert, // user-alert
UserKey, // user-key
UserConversation, // user-conversation
Database, // database
DatabaseSearch, // database-search
ListAlt, // list-alt
HazardSign, // hazard-sign
Hazard, // hazard
StopSign, // stop-sign
Lab, // lab
LabAlt, // lab-alt
IceCream, // ice-cream
IceLolly, // ice-lolly
IceLollyTasted, // ice-lolly-tasted
Invoice, // invoice
CartTick, // cart-tick
Hourglass, // hourglass
Cat, // cat
Lamp, // lamp
ScaleClassic, // scale-classic
EyePlus, // eye-plus
EyeMinus, // eye-minus
Quote, // quote
Bitcoin, // bitcoin
Yen, // yen
Ruble, // ruble
Erase, // erase
Podcast, // podcast
Firework, // firework
Scale, // scale
King, // king
Queen, // queen
Pawn, // pawn
Bishop, // bishop
Knight, // knight
MicMute, // mic-mute
Voicemail, // voicemail
Paragraph, // paragraph
PersonWalking, // person-walking
PersonWheelchair, // person-wheelchair
Underground, // underground
CarHov, // car-hov
CarRental, // car-rental
Transport, // transport
Taxi, // taxi
IceCreamNo, // ice-cream-no
UkRatingU, // uk-rat-u
UkRatingPG, // uk-rat-pg
UkRating12a, // uk-rat-12a
UkRating12, // uk-rat-12
UkRating15, // uk-rat-15
UkRating18, // uk-rat-18
UkRatingR18, // uk-rat-r18
Tv, // tv
Sms, // sms
Mms, // mms
UsRatingG, // us-rat-g
UsRatingPG, // us-rat-pg
UsRatingPG13, // us-rat-pg-13
UsRatingRestricted, // us-rat-restricted
UsRatingNoOne17, // us-rat-no-one-17
Equalizer, // equalizer
Speakers, // speakers
RemoteControl, // remote-control
RemoteControlTv, // remote-control-tv
Shredder, // shredder
FolderHeart, // folder-heart
PersonRunning, // person-running
Person, // person
Voice, // voice
Stethoscope, // stethoscope
Hotspot, // hotspot
Activity, // activity
Watch, // watch
ScissorsAlt, // scissors-alt
CarWheel, // car-wheel
ChevronUp, // chevron-up
ChevronDown, // chevron-down
Superscript, // superscript
Subscript, // subscript
TextSize, // text-size
TextColor, // text-color
TextBackground, // text-background
ModalWindow, // modal-window
Newspaper, // newspaper
Tractor, // tractor
    }
}