using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PDQ.Framework.Web.CssIcons
{
    public enum GlyphHalflings
    {
        HandDown, // hand-down
        CircleArrowRight, // circle-arrow-right
        CircleArrowLeft, // circle-arrow-left
        CircleArrowTop, // circle-arrow-top
        CircleArrowDown, // circle-arrow-down
        Globe, // globe
        GlyphWrench, // glyph-wrench
        Tasks, // tasks
        Filter, // filter
        GlyphBriefcase, // glyph-briefcase
        Fullscreen, // fullscreen
        Dashboard, // dashboard
        GlyphPaperclip, // glyph-paperclip
        HeartEmpty, // heart-empty
        Link, // link
        Phone, // phone
        GlyphPushpin, // glyph-pushpin
        Euro, // euro
        Usd, // usd
        Gbp, // gbp
        Sort, // sort
        SortByAlphabet, // sort-by-alphabet
        SortByAlphabetAlt, // sort-by-alphabet-alt
        SortByOrder, // sort-by-order
        SortByOrderAlt, // sort-by-order-alt
        SortByAttributes, // sort-by-attributes
        SortByAttributesAlt, // sort-by-attributes-alt
        Unchecked, // unchecked
        Expand, // expand
        Collapse, // collapse
        CollapseTop, // collapse-top
        LogIn, // log-in
        Flash, // flash
        LogOut, // log-out
        NewWindow, // new-window
        Record, // record
        Save, // save
        Open, // open
        Saved, // saved
        Import, // import
        Export, // export
        Send, // send
        FloppyDisk, // floppy-disk
        FloppySaved, // floppy-saved
        FloppyRemove, // floppy-remove
        FloppySave, // floppy-save
        FloppyOpen, // floppy-open
        CreditCard, // credit-card
        Transfer, // transfer
        Cutlery, // cutlery
        Header, // header
        Compressed, // compressed
        Earphone, // earphone
        PhoneAlt, // phone-alt
        Tower, // tower
        Stats, // stats
        SdVideo, // sd-video
        HdVideo, // hd-video
        Subtitles, // subtitles
        SoundStereo, // sound-stereo
        SoundDolby, // sound-dolby
        Sound51, // sound-5-1
        Sound61, // sound-6-1
        Sound71, // sound-7-1
        CopyrightMark, // copyright-mark
        RegistrationMark, // registration-mark
        Cloud, // cloud
        CloudDownload, // cloud-download
        CloudUpload, // cloud-upload
        TreeConifer, // tree-conifer
        TreeDeciduous, // tree-deciduous
        Cd, // cd
        SaveFile, // save-file
        OpenFile, // open-file
        LevelUp, // level-up
        Copy, // copy
        Paste, // paste
        Door, // door
        Key, // key
        Alert, // alert
        Equalizer, // equalizer
        King, // king
        Queen, // queen
        Pawn, // pawn
        Bishop, // bishop
        Knight, // knight
        BabyFormula, // baby-formula
        Tent, // tent
        Blackboard, // blackboard
        Bed, // bed
        Apple, // apple
        Erase, // erase
        Hourglass, // hourglass
        Lamp, // lamp
        Duplicate, // duplicate
        PiggyBank, // piggy-bank
        Scissors, // scissors
        Bitcoin, // bitcoin
        Yen, // yen
        Ruble, // ruble
        Scale, // scale
        IceLolly, // ice-lolly
        IceLollyTasted, // ice-lolly-tasted
        Education, // education
        OptionHorizontal, // option-horizontal
        OptionVertical, // option-vertical
        MenuHamburger, // menu-hamburger
        ModalWindow, // modal-window
        Oil, // oil
        Grain, // grain
        Sunglasses, // sunglasses
        TextSize, // text-size
        TextColor, // text-color
        TextBackground, // text-background
        ObjectAlignTop, // object-align-top
        ObjectAlignBottom, // object-align-bottom
        ObjectAlignHorizontal, // object-align-horizontal
        ObjectAlignLeft, // object-align-left
        ObjectAlignVertical, // object-align-vertical
        ObjectAlignRight, // object-align-right
        TriangleRight, // triangle-right
        TriangleLeft, // triangle-left
        TriangleBottom, // triangle-bottom
        TriangleTop, // triangle-top
        Terminal, // terminal
        Superscript, // superscript
        Subscript, // subscript
        MenuLeft, // menu-left
        MenuRight, // menu-right
        MenuDown, // menu-down
        MenuUp, // menu-up
    }
}
