using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PDQ.Framework.Web.CssIcons
{
    public enum GlyphSocial
    {
Pinterest, //pinterest
Dropbox, //dropbox
GooglePlus, //google-plus
Jolicloud, //jolicloud
Yahoo, //yahoo
Blogger, //blogger
Picasa, //picasa
Amazon, //amazon
Tumblr, //tumblr
Wordpress, //wordpress
Instapaper, //instapaper
Evernote, //evernote
Xing, //xing
Zootool, //zootool
Dribbble, //dribbble
Deviantart, //deviantart
ReadItLater, //read-it-later
LinkedIn, //linked-in
Forrst, //forrst
Pinboard, //pinboard
Behance, //behance
Github, //github
Youtube, //youtube
Skitch, //skitch
Foursquare, //foursquare
Quora, //quora
Badoo, //badoo
Spotify, //spotify
Stumbleupon, //stumbleupon
Readability, //readability
Facebook, //facebook
Twitter, //twitter
Instagram, //instagram
PosterousSpaces, //posterous-spaces
Vimeo, //vimeo
Flickr, //flickr
LastFm, //last-fm
Rss, //rss
Skype, //skype
Email, //e-mail
Vine, //vine
Myspace, //myspace
Goodreads, //goodreads
Apple, //apple
Windows, //windows
Yelp, //yelp
Playstation, //playstation
Xbox, //xbox
Android, //android
Ios, //ios
Wikipedia, //wikipedia
Pocket, //pocket
Steam, //steam
Souncloud, //souncloud
Slideshare, //slideshare
Netflix, //netflix
Paypal, //paypal
GoogleDrive, //google-drive
LinuxFoundation, //linux-foundation
Ebay //ebay
    }
}
